import {test,expect} from '@playwright/test';
test('public multi-traveller booking, terms, payment, QR, lookup and coordinator check-in',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const yatras=(await (await page.request.get('/api/yatras')).json()).yatras;const y=yatras[0];
 await page.goto('/');await expect(page.getByRole('navigation').first()).toBeVisible();
 await page.goto('/yatras');await expect(page.getByText(y.name).first()).toBeVisible();
 await page.goto('/yatras/'+y.slug);await expect(page.getByRole('heading',{name:y.name,exact:true})).toBeVisible();
 await page.goto('/yatras/'+y.slug+'/book');await page.getByLabel('Full name *',{exact:true}).nth(0).fill('Browser Family');await page.getByLabel('Mobile *',{exact:true}).fill('9876543210');await page.getByLabel('Full name *',{exact:true}).nth(1).fill('First Traveller');await page.getByLabel('Age *',{exact:true}).fill('30');
 await page.getByRole('button',{name:'Add',exact:true}).click();await page.getByLabel('Full name *',{exact:true}).nth(2).fill('Second Traveller');await page.getByLabel('Age *',{exact:true}).nth(1).fill('25');
 await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('heading',{name:'Review your booking'})).toBeVisible();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Continue',exact:true}).click();
 const lookup=page.waitForResponse(r=>r.url().endsWith('/api/bookings/lookup')&&r.request().method()==='POST');await page.getByRole('button',{name:'Success',exact:true}).click();const booking=(await (await lookup).json()).booking;
 await expect(page.getByRole('heading',{name:'Booking Confirmed'})).toBeVisible();await expect(page.locator('canvas')).toBeVisible();expect(booking.travellerCount).toBe(2);expect(booking.customerSnapshot).toBeUndefined();
 await page.goto('/booking');await page.getByLabel('Booking ID',{exact:true}).fill(booking.reference);await page.getByLabel('Mobile number').fill('9876543210');await page.getByRole('button',{name:'Find my booking'}).click();await expect(page.locator('canvas')).toBeVisible();
 await page.goto('/coordinator');await page.getByLabel('Email',{exact:true}).fill('coordinator@example.test');await page.getByLabel('Password',{exact:true}).fill('Disposable-test-only-123!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button').filter({hasText:y.name}).click();await page.getByPlaceholder('GMY-TKT-…').fill(booking.ticket.token);await page.getByRole('button',{name:'Check',exact:true}).click();await expect(page.getByText('Valid Ticket',{exact:true})).toBeVisible();await page.getByRole('button',{name:'CHECK IN ALL (2)'}).click();await expect(page.getByText('Already Checked In',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Scan another'}).click();await page.getByPlaceholder('GMY-TKT-…').fill(booking.ticket.token);await page.getByRole('button',{name:'Check',exact:true}).click();await expect(page.getByText('Already Checked In',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Change yatra'}).click();await page.getByRole('button').filter({hasText:yatras[1].name}).click();await page.getByPlaceholder('GMY-TKT-…').fill(booking.ticket.token);await page.getByRole('button',{name:'Check',exact:true}).click();await expect(page.getByText('This ticket belongs to a different yatra.')).toBeVisible();expect(errors).toEqual([]);
});
test('admin login, management, manual booking, reports and payment settings',async({page})=>{
 await page.goto('/admin/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.test');await page.getByLabel('Password',{exact:true}).fill('Disposable-test-only-123!');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/admin$/);
 await page.getByRole('link',{name:'Yatras',exact:true}).click();await expect(page.getByRole('button',{name:/New yatra/i})).toBeVisible();
 await page.getByRole('link',{name:'Bookings',exact:true}).click();await page.getByRole('button',{name:/Manual booking/i}).click();await page.getByLabel('Yatra',{exact:true}).selectOption({index:1});await page.getByLabel('Customer name').fill('Offline Customer');await page.getByLabel('Mobile',{exact:true}).fill('9876543201');await page.getByLabel('Traveller 1',{exact:true}).fill('Offline Traveller');await page.getByLabel('Age',{exact:true}).fill('42');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create & confirm'}).click();await expect(page.getByText('Manual booking created & confirmed')).toBeVisible();
 await page.getByRole('link',{name:'Customers',exact:true}).click();await expect(page.getByText('Offline Customer').first()).toBeVisible();await page.getByRole('link',{name:'Reports',exact:true}).click();await expect(page.getByRole('heading',{name:/Reports/i})).toBeVisible();await page.getByRole('link',{name:'Payments',exact:true}).click();await expect(page.getByRole('heading',{name:'Razorpay configuration'})).toBeVisible();await expect(page.getByLabel('Test mode')).toBeChecked();
});
test('mobile browsing fits viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('main')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.goto('/yatras');await expect(page.getByRole('heading').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
