import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import Razorpay from 'razorpay';
import {RazorpayPaymentProvider,verifyRazorpayWebhook} from '../lib/payments/razorpay-provider';
import {encryptPaymentSecret,decryptPaymentSecret} from '../lib/payments/config-crypto';
const secret='unit-test-secret';
const input={orderId:'order_example',bookingReference:'GMY-2099-00001',amount:100,providerPaymentId:'pay_example',providerSignature:createHmac('sha256',secret).update('order_example|pay_example').digest('hex')};
function provider(change:Record<string,unknown>={}){const client={payments:{fetch:async()=>({order_id:input.orderId,amount:10000,currency:'INR',status:'captured',...change})},orders:{fetch:async()=>({amount:10000,currency:'INR',receipt:input.bookingReference}),create:async()=>({id:input.orderId})}};return new RazorpayPaymentProvider({keyId:'rzp_test_example',secret},client as unknown as Razorpay);}
test('Razorpay signature and captured payment binding are required',async()=>{assert.equal((await provider().verifyPayment(input)).status,'PAID');for(const patch of [{amount:99},{currency:'USD'},{order_id:'other'}])await assert.rejects(provider(patch).verifyPayment(input),/binding/);assert.equal((await provider({status:'authorized'}).verifyPayment(input)).status,'PENDING');assert.equal((await provider({status:'failed'}).verifyPayment(input)).status,'PENDING');await assert.rejects(provider().verifyPayment({...input,providerSignature:'bad'}),/signature/);await assert.rejects(provider().verifyPayment({...input,providerSignature:undefined}),/signature/);});
test('Razorpay order amount validation and key-only checkout response',async()=>{const p=provider();assert.equal((await p.createOrder({amount:100,bookingReference:input.bookingReference})).keyId,'rzp_test_example');await assert.rejects(p.createOrder({amount:Infinity,bookingReference:'test'}));await assert.rejects(p.createOrder({amount:1,currency:'USD',bookingReference:'test'}));});
test('Webhook signature uses exact raw bytes and rejects forged or missing signatures',()=>{const body='{"event":"payment.captured"}';const sig=createHmac('sha256',secret).update(body).digest('hex');assert.equal(verifyRazorpayWebhook(body,sig,secret),true);assert.equal(verifyRazorpayWebhook(body+' ',sig,secret),false);assert.equal(verifyRazorpayWebhook(body,null,secret),false);assert.equal(verifyRazorpayWebhook(body,'界'.repeat(64),secret),false);});
test('Payment secrets use authenticated encryption and reject tampering',()=>{process.env.PAYMENT_CONFIG_ENCRYPTION_KEY='test-only-encryption-key-32-characters';const encrypted=encryptPaymentSecret(secret);assert.notEqual(encrypted,secret);assert.equal(decryptPaymentSecret(encrypted),secret);const parts=encrypted.split('.');parts[2]='AAAA';assert.throws(()=>decryptPaymentSecret(parts.join('.')));});
