'use client';
import {useEffect,useState} from 'react';
import {AdminShell} from '@/components/admin/admin-shell';
import {staffApi,ADMIN_TOKEN} from '@/lib/staff-client';
type Config={keyId:string;testMode:boolean;enabled:boolean;keySecretSaved:boolean;webhookSecretSaved:boolean};
export default function Payments(){
 const [config,setConfig]=useState<Config|null>(null);const [keySecret,setKeySecret]=useState('');const [webhookSecret,setWebhookSecret]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{staffApi<Config>(ADMIN_TOKEN,'/admin/payment-config').then(setConfig).catch(()=>setMessage('Could not load payment settings'));},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{setConfig(await staffApi<Config>(ADMIN_TOKEN,'/admin/payment-config',{method:'PUT',body:JSON.stringify({...config,keySecret,webhookSecret})}));setKeySecret('');setWebhookSecret('');setMessage('Payment settings saved');}catch(e){setMessage(e instanceof Error?e.message:'Could not save settings');}finally{setBusy(false);}}
 return <AdminShell title="Payments"><div className="mx-auto max-w-3xl rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Razorpay configuration</h2><p className="mt-2 text-sm text-slate-600">INR · https://api.razorpay.com/v1</p>{message&&<p role="status" className="my-4">{message}</p>}{!config?<p>Loading settings…</p>:<form onSubmit={save} className="mt-6 space-y-5"><label className="block">API key / Key ID<input required className="gy-input mt-2" value={config.keyId} onChange={e=>setConfig({...config,keyId:e.target.value})}/></label><label className="block">API secret {config.keySecretSaved?'(saved)':''}<input type="password" autoComplete="new-password" className="gy-input mt-2" value={keySecret} placeholder="Leave blank to keep saved secret" onChange={e=>setKeySecret(e.target.value)}/></label><label className="block">Webhook secret {config.webhookSecretSaved?'(saved)':''}<input type="password" autoComplete="new-password" className="gy-input mt-2" value={webhookSecret} placeholder="Leave blank to keep saved secret" onChange={e=>setWebhookSecret(e.target.value)}/></label><label className="flex gap-3"><input type="checkbox" checked={config.testMode} onChange={e=>setConfig({...config,testMode:e.target.checked})}/>Test mode</label><label className="flex gap-3"><input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/>Gateway enabled</label><p className="rounded-xl bg-amber-50 p-4 text-sm">Verify test payments end to end before enabling live payments. Configure the webhook endpoint /api/payments/webhook for payment.captured and order.paid.</p><p className="rounded-xl bg-emerald-50 p-4 text-sm">Secrets are encrypted before storage and never returned by the API. Blank secret fields preserve saved values.</p><button disabled={busy} className="btn-primary">{busy?'Saving…':'Save payment configuration'}</button></form>}</div></AdminShell>;
}
